### ISSUE TITLE
Error with type in read_stockholm_msa

### ISSUE THREAD

**Issue by piosierra** [brendanf/inferrnal#1]
Hello,

I get error "unknown sequence type: DNA" when trying to read a DNA stockholm file. 

> read_stockholm_msa(file, type = "DNA")
Error in match.arg(type) : 'arg' should be one of “RNA”, “DNA”, “AA”

If I instead use lowercase:
> read_stockholm_msa(file, type = "dna")
Error in match.arg(type) : 'arg' should be one of “RNA”, “DNA”, “AA”

Looking at the code it looks as if they are not converted properly. The function requires uppercase, but then it matches to lowercase. Can that be the problem?

Thanks.

**Comment by brendanf** [comment]
Sorry!  This was a bug I already fixed in the Bioconductor submission branch, but forgot to merge into master.  Give it a try now!

**Comment by piosierra** [comment]
Sorry, I forgot to comment on this. Thanks!
